% ATLAS - deConfUSIon implementation module.
% Initialize with deConfUSIon_setup; see docs/code_map.md for callers.
%   deConfUSIon_apply_rgb2acr
%   deConfUSIon_auto_register_3d
%   deConfUSIon_prepare_atlas
%   deConfUSIon_region_groups
%   fusiAtlasBrainMask
%   fusiAtlasPairedTransformFile
%   fusiAtlasRecordingGrid3D
%   fusiAtlasReferenceSlabs
%   fusiAtlasRegionCatalog
%   fusiAtlasRegionGrouping
%   fusiAtlasRegionInput
%   fusiAtlasRegroupUnderlay3D
%   fusiAtlasSearchContext
%   fusiAtlasSizeMatrix
%   fusiAtlasTransformFolder
%   fusiAtlasUnderlayChoices
%   fusiAtlasUnderlayDisplay3D
%   fusiAtlasUnderlayLibrary2D
%   fusiAtlasUnderlayView3D
%   fusiBregmaAnchors
%   fusiCachedAtlasUnderlay3D
%   fusiCachedAtlasUnderlayView3D
%   fusiChooseAtlasTransformFile
%   fusiChooseUnderlayFile
%   fusiCoronalSliceGuide
%   fusiFindAtlasUnderlay3D
%   fusiFitCoronalAnchors
%   fusiImportSnapAdjustment
%   fusiOpenSnapWorkspace
%   fusiReadAtlasUnderlay3D
%   fusiRegistrationConfigureSlices
%   fusiRegistrationDisplayVolume
%   fusiRegistrationFeatures
%   fusiRegistrationOverlayAlpha
%   fusiRegistrationOverlayAppearance
%   fusiRegistrationSliceSupport
%   fusiSaveAtlasUnderlays3D
%   fusiSnapOverlayWorkspace
%   fusiSnapVesselContrast
%   fusiUnderlayPickerOptions
%   fusiWarpAtlasForDisplay
