function [Tgrid,info]=fusiAtlasRecordingGrid3D(T)
% Atlas XY with one coronal AP sample per acquired source slice.
g=T.scanGeometry;
assert(all(isfield(g,{'convention','originalSize','permutation','originalSpacingUm','atlasVoxelSizeUm'})) && ...
 numel(g.originalSize)==3 && isequal(sort(g.permutation),1:3) && ...
 all(isfinite(g.originalSize) & g.originalSize>=2 & g.originalSize==round(g.originalSize)) && ...
 numel(g.originalSpacingUm)==3 && numel(g.atlasVoxelSizeUm)==3 && ...
 all(isfinite([g.originalSpacingUm g.atlasVoxelSizeUm])) && all([g.originalSpacingUm g.atlasVoxelSizeUm]>0), ...
 'deConfUSIon:AtlasSliceGeometry','The saved 3D alignment has incomplete or invalid voxel geometry.');
assert(isequal(size(T.M),[4 4]) && all(isfinite(T.M(:))) && rcond(double(T.M))>1e-10 && ...
 norm(double(T.M(:,4))-[0;0;0;1])<1e-8 && det(double(T.M(1:3,1:3)))>0, ...
 'deConfUSIon:AtlasSliceGeometry','The saved 3D affine is invalid or contains an unexpected reflection.');
assert(strcmp(g.convention,'coronal_stack_v2') && g.permutation(1)==3, ...
 'deConfUSIon:AtlasSliceGeometry','Use the confirmed coronal-stack geometry for this 3D recording.');
sz=double(g.originalSize);av=double(g.atlasVoxelSizeUm(:)');sv=double(g.originalSpacingUm(g.permutation));
n=sz(3);preparedCenter=1+(sz(g.permutation)-1).*sv./av/2;
source=1:n;ap=source;if isfield(g,'flipAxes') && ismember(1,g.flipAxes),ap=n+1-ap;end
ap=1+(ap-1)*sv(1)/av(1);
points=[repmat(preparedCenter(2),n,1),ap(:),repmat(preparedCenter(3),n,1),ones(n,1)]*double(T.M);
[centers,order]=sort(points(:,2));centers=centers';source=source(order);
step=sv(1)/av(1)*abs(T.M(2,2));
assert(isfinite(step) && step>1e-6,'deConfUSIon:AtlasSliceGeometry', ...
 'The scan AP axis is perpendicular to atlas AP. Review the 3D orientation before coronal slicing.');
canonical=double(T.size);if isfield(T,'atlasCanonicalSize'),canonical=double(T.atlasCanonicalSize);end
assert(numel(canonical)==3 && all(isfinite(canonical) & canonical>=2 & canonical==round(canonical)), ...
 'deConfUSIon:AtlasSliceGeometry','The saved 3D atlas grid is invalid.');
sampling=eye(4);sampling(2,2)=1/step;sampling(4,2)=1-centers(1)/step;
Tgrid=T;Tgrid.M=double(T.M)*sampling;
if isfield(Tgrid,'warpA'),Tgrid.warpA=Tgrid.M;end
Tgrid.size=[n canonical(2:3)];Tgrid.atlasCanonicalSize=Tgrid.size;Tgrid.outSize=Tgrid.size;
Tgrid.displayPermutation=[2 3 1];Tgrid.outputSize=Tgrid.size([2 3 1]);
info=struct('sourceSlices',source,'atlasAPIndices',centers,'originalAtlasSizeAPDVLR',canonical, ...
 'outputSizeYXZ',Tgrid.outputSize,'voxelSizeYXZUm',[av(2:3) av(1)*step], ...
 'samplingRule','Coronal atlas planes through transformed native slice centers. Atlas XY spacing is retained.');
end
