function bundle=fusiSaveStepMotorUnderlays2D(session,sessionFile)
% Save full atlas planes in source-slice order beside one reviewed session.
sessionFile=char(sessionFile);folder=fullfile(fileparts(sessionFile),'AtlasUnderlays');
assert(strcmp(fusiAnalysisOutputPath(folder),folder),'deConfUSIon:RawOutput', ...
 'Step-motor atlas outputs must be saved in AnalysedData, not RawData.');
assert(~isfolder(folder),'deConfUSIon:AtlasBundleExists','This session already has an underlay bundle. Save a new session instead.');
files=session.files;first=session.Reg2DList{1};
shape=double(first.outputSize(1:2));
[entries,names]=fusiAtlasUnderlayLibrary2D(files,[shape numel(files)]);
assert(numel(entries)==4,'deConfUSIon:StepMotorUnderlays', ...
 'Each saved plane must contain histology, vascular and region labels with their region table.');
mkdir(folder);
bundle=struct('folder',folder,'sessionFile',sessionFile,'histology',fullfile(folder,'Histology.mat'), ...
 'vascular',fullfile(folder,'Vascular.mat'),'regionsAll',fullfile(folder,'Regions_All.mat'), ...
 'regionsMerged',fullfile(folder,'Regions_Merged.mat'),'readme',fullfile(folder,'README.txt'));
atlasIndices=cellfun(@(r)r.atlasSliceIndex,session.Reg2DList);
fields={'histology','vascular','regionsAll','regionsMerged'};
for k=1:numel(entries)
 entry=entries{k};brainImage=entry.data;atlasUnderlay=entry.data;atlasMode=entry.meta.atlasMode; %#ok<NASGU>
 atlasInfoRegions=entry.meta.regionInfo;atlasRegionLabels=entry.meta.regionLabels; %#ok<NASGU>
 stepMotorUnderlayMeta=struct('kind','deConfUSIon_step_motor_registration_underlay','version',1, ...
  'sessionFileRelative',fullfile('..','StepMotor_Reg2D_Session.mat'), ...
  'sourceNSlices',session.sourceNSlices,'sourceSliceIndices',session.savedSourceIdx, ...
  'atlasSliceIndices',atlasIndices,'gridSizeYXZ',[shape numel(files)], ...
  'voxelSizeUm',entry.meta.voxelSizeUm,'arrayOrder','row-column-source slice', ...
  'grouping',entry.grouping,'choiceName',names{k}); %#ok<NASGU>
 save(bundle.(fields{k}),'brainImage','atlasUnderlay','atlasMode','atlasInfoRegions', ...
  'atlasRegionLabels','stepMotorUnderlayMeta','-v7');
 if entry.meta.isColor
  filename=fullfile(folder,[fields{k} '_region_list.tsv']);
  fid=fopen(filename,'w');assert(fid>=0,'Could not save region list.');guard=onCleanup(@()fclose(fid));
  fprintf(fid,'ID\tAbbreviation\tRegion\n');
  for j=1:numel(atlasInfoRegions.name),fprintf(fid,'%d\t%s\t%s\n',j,atlasInfoRegions.acr{j},atlasInfoRegions.name{j});end
  clear guard;
 end
end
fid=fopen(bundle.readme,'w');assert(fid>=0,'Could not save underlay guide.');guard=onCleanup(@()fclose(fid)); %#ok<NASGU>
fprintf(fid,['Reviewed step-motor atlas bundle\n\n' ...
 'In SCM GUI: Underlay > LOAD ATLAS FOLDER and choose this session or AtlasUnderlays folder.\n' ...
 'Or LOAD NEW UNDERLAY and choose Histology.mat, Vascular.mat or Regions_*.mat.\n' ...
 'All saved source planes are loaded together, then switch modes in the Atlas underlay dropdown.\n' ...
 'The paired functional data is warped with the exact per-slice transforms from this session.\n' ...
 'Full atlas planes are preserved; AP gaps are not interpolated or stretched.\n' ...
 'Missing source slices remain excluded. Image left/right is not changed.\n\n' ...
 'Output plane\tSource slice\tAtlas coronal slice\n']);
for k=1:numel(files),fprintf(fid,'%d\t%d\t%d\n',k,session.savedSourceIdx(k),atlasIndices(k));end
end
