function [out, stats] = scrubbing(data, TR, saveRoot, tag, cfgIn)
% ==========================================================
% SCRUBBING (MEMORY-SAFE)
%   - Detection: DVARS or Global Signal
%   - Interp   : Linear or PCHIP
% Optional trimming
% Full QC PNG saving
% MATLAB 2017b compatible
% ==========================================================

deConfUSIon_setup();
if nargin < 4 || isempty(tag)
    tag = datestr(now,'yyyymmdd_HHMMSS');
end
if nargin < 3 || isempty(saveRoot)
    saveRoot = pwd;
end
if numel(TR) > 1, TR = TR(end); end
TR = double(TR);

% ---------------- FORCE 4D ----------------
data = single(data);
sz = size(data);

if ndims(data) == 3
    Y = sz(1); X = sz(2); T = sz(3);
    Z = 1;
    data4D = reshape(data, Y, X, 1, T);
elseif ndims(data) == 4
    Y = sz(1); X = sz(2); Z = sz(3); T = sz(4);
    data4D = data;
else
    error('Data must be 3D or 4D.');
end

origT = T;
trimmed = false;
trimStartVol = 0;
trimEndVol   = 0;

% ---------------- SINGLE SCRUBBING SETUP POPUP ----------------
if nargin >= 5 && isstruct(cfgIn)
    cfg = cfgIn;
    if ~isfield(cfg,'cancelled'), cfg.cancelled=false; end
    if isfield(cfg,'scrubMetric'), cfg.method=cfg.scrubMetric; end
    if isfield(cfg,'scrubInterpolation'), cfg.interpMethod=lower(cfg.scrubInterpolation); end
    if isfield(cfg,'scrubTrim'), cfg.doTrim=cfg.scrubTrim; end
else
    cfg = showScrubbingSetupDialog();
end

if isempty(cfg) || ~isstruct(cfg) || cfg.cancelled
    out = [];
    stats = struct();
    stats.cancelled = true;
    return;
end

method = cfg.method;
interpMethod = cfg.interpMethod;
showProgress=true; if isfield(cfg,'showProgress'), showProgress=cfg.showProgress; end
progress=deConfUSIon_ui('progress','Motion correction - scrubbing',showProgress);
progressGuard=onCleanup(@()deConfUSIon_ui('progressclose',progress)); %#ok<NASGU>

% Defaults:
%   - DVARS
%   - Linear interpolation
%   - No trimming
if cfg.doTrim
    startSec = cfg.trimStartSec;
    endSec   = cfg.trimEndSec;

    if ~isfinite(startSec), startSec = 0; end
    if ~isfinite(endSec),   endSec   = 0; end

    trimStartVol = max(0, round(startSec/TR));
    trimEndVol   = max(0, round(endSec/TR));

    newStart = trimStartVol + 1;
    newEnd   = T - trimEndVol;

    if newEnd > newStart
        data4D = data4D(:,:,:,newStart:newEnd);
        T = size(data4D,4);
        trimmed = true;
    else
        trimmed = false;
        trimStartVol = 0;
        trimEndVol   = 0;
    end
end

% ---------------- MASK ----------------
meanVol = mean(data4D,4);
mx = max(meanVol(:));
if mx <= 0 || ~isfinite(mx)
    mask = true(size(meanVol));
else
    mask = meanVol > 0.05 * mx;
    if ~any(mask(:)), mask = true(size(meanVol)); end
end

% ---------------- FLATTEN (SINGLE!) ----------------
flatAll = reshape(data4D, [], T);     % single [V x T]
maskVec = mask(:);
maskIndices=find(maskVec);

% ---------------- METRIC ----------------
chunkV=max(1,floor(32*1024^2/(8*T*3)));
globalSum=zeros(1,T); differenceSum=zeros(1,max(0,T-1));
for a=1:chunkV:numel(maskIndices)
    b=min(numel(maskIndices),a+chunkV-1); block=flatAll(maskIndices(a:b),:);
    globalSum=globalSum+sum(double(block),1);
    if strcmp(method,'DVARS'), delta=diff(block,1,2); differenceSum=differenceSum+sum(double(delta).^2,1); end
    deConfUSIon_ui('progressupdate',progress,.05+.3*b/numel(maskIndices),'Computing scrubbing metrics');
end
globalSig=globalSum/numel(maskIndices);
if strcmp(method,'DVARS'), metric=[0 sqrt(differenceSum/numel(maskIndices))];
elseif strcmp(method,'Global Signal'), metric=globalSig;
else, error('deConfUSIon:ScrubMetric','Unknown scrubbing metric: %s',method); end
clear block delta;

% ---------------- THRESHOLD ----------------
medVal = median(metric);
madVal = mad(metric, 1);     % median absolute deviation (robust)
k = 2.5;
TH = medVal + k * madVal;

badMask = metric > TH;
badIdx  = find(badMask);
goodIdx = find(~badMask);

% ---------------- INTERPOLATE (CHUNKED, ONLY BAD FRAMES) ----------------
% This avoids creating interpData for ALL frames.
if ~isempty(badIdx) && numel(goodIdx) >= 2

    V = size(flatAll,1);
    % Chunk size: keep temporary arrays reasonable
    chunkV = min(2000,max(1,floor(32*1024^2/(8*T*3))));

    tGood = goodIdx(:);          % column vector
    tBad  = badIdx(:);           % column vector

    for v0 = 1:chunkV:V
        v1 = min(V, v0 + chunkV - 1);

        % Ygood: [numGood x chunk] in double for interp1 stability
        Ygood = double(flatAll(v0:v1, tGood)).';   % transpose -> [G x chunk]

        % Interpolate ONLY bad times -> returns [B x chunk]
        Ybad = interp1(tGood, Ygood, tBad, interpMethod, 'extrap');

        % Write back into flatAll (single)
        flatAll(v0:v1, tBad) = single(Ybad.');     % transpose back -> [chunk x B]
        deConfUSIon_ui('progressupdate',progress,.35+.6*v1/V,'Interpolating flagged frames');
    end
end

out = reshape(flatAll, Y, X, Z, T);
if numel(sz)==3, out=reshape(out,Y,X,T); end
deConfUSIon_ui('progressupdate',progress,.95,'Saving scrubbing QC');

% ---------------- STATS ----------------
stats.originalVolumes = origT;
stats.finalVolumes    = T;
stats.flaggedVolumes  = numel(badIdx);
stats.removedVolumes  = numel(badIdx);                 % keep compatibility
stats.percentFlagged  = 100 * numel(badIdx) / max(1,T);
stats.percentRemoved  = stats.percentFlagged;          % keep compatibility
stats.threshold       = TH;
stats.method          = method;
stats.interpMethod    = interpMethod;

stats.trimmed       = trimmed;
stats.trimStartVol  = trimStartVol;
stats.trimEndVol    = trimEndVol;
stats.trimStartSec  = trimStartVol * TR;
stats.trimEndSec    = trimEndVol   * TR;
stats.newTotalTime  = T * TR;

% ---------------- QC SAVE ----------------
qcDir = fullfile(saveRoot,'Preprocessing','QC_scrubbing');
if ~exist(qcDir,'dir'), mkdir(qcDir); end

qcFile = fullfile(qcDir, sprintf('QC_scrubbing_%s_%s_%s.png', method, interpMethod, tag));


fig = figure('Visible','off','Color','w');

subplot(2,1,1)
plot(metric,'k','LineWidth',1); hold on
plot([1 length(metric)], [TH TH], 'r--', 'LineWidth',1.5)
plot(badIdx, metric(badIdx),'ro','MarkerSize',4)
title(sprintf('Detection Metric - %s', method))
legend({'Metric','Threshold','Flagged volumes'},'Location','best')
xlabel('Volume'); ylabel('Metric')

subplot(2,1,2)
plot(globalSig,'b','LineWidth',1); hold on
plot(badIdx, globalSig(badIdx),'ro','MarkerSize',4)
title('Global Signal (reference)')
legend({'Global signal','Flagged volumes'},'Location','best')
xlabel('Volume'); ylabel('Signal')

saveas(fig, qcFile);
close(fig);

stats.qcFile = qcFile;
function cfg = showScrubbingSetupDialog()
% Dark one-window setup dialog for scrubbing.
% MATLAB 2017b compatible.
%
% Defaults:
%   - Detection: DVARS
%   - Interpolation: Linear
%   - Trimming: OFF / no trimming

cfg = struct();
cfg.cancelled    = true;
cfg.method       = 'DVARS';
cfg.interpMethod = 'linear';
cfg.doTrim       = false;
cfg.trimStartSec = 0;
cfg.trimEndSec   = 0;

bg      = [0.06 0.06 0.07];
bg2     = [0.10 0.10 0.11];
bg3     = [0.14 0.14 0.16];
fg      = [0.96 0.96 0.96];
fgDim   = [0.72 0.72 0.75];
cyanCol = [0.25 0.75 1.00];
green   = [0.15 0.70 0.35];
red     = [0.80 0.25 0.25];
blue    = [0.25 0.45 0.95];
orange  = [1.00 0.65 0.20];

dlg = figure( ...
    'Name','Scrubbing Setup', ...
    'Color',bg, ...
    'MenuBar','none', ...
    'ToolBar','none', ...
    'NumberTitle','off', ...
    'Resize','off', ...
    'Units','pixels', ...
    'Position',[200 120 760 500], ...
    'WindowStyle','modal', ...
    'Visible','off', ...
    'CloseRequestFcn',@onCancel);

try
    movegui(dlg,'center');
catch
end

% ---------------------------------------------------------------------
% Header
% ---------------------------------------------------------------------
uicontrol('Parent',dlg,'Style','text', ...
    'Units','normalized', ...
    'Position',[0.04 0.91 0.92 0.06], ...
    'BackgroundColor',bg, ...
    'ForegroundColor',fg, ...
    'FontName','Arial', ...
    'FontSize',20, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'String','Scrubbing Setup');

uicontrol('Parent',dlg,'Style','text', ...
    'Units','normalized', ...
    'Position',[0.04 0.855 0.92 0.045], ...
    'BackgroundColor',bg, ...
    'ForegroundColor',fgDim, ...
    'FontName','Arial', ...
    'FontSize',12, ...
    'HorizontalAlignment','left', ...
    'String','Recommended default is DVARS + Linear interpolation + No trimming.');

% ---------------------------------------------------------------------
% Detection method
% ---------------------------------------------------------------------
methodGroup = uibuttongroup('Parent',dlg, ...
    'Units','normalized', ...
    'Position',[0.04 0.59 0.44 0.23], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',fg, ...
    'Title','Detection metric', ...
    'FontName','Arial', ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'BorderType','line');

rbDVARS = uicontrol('Parent',methodGroup, ...
    'Style','radiobutton', ...
    'Units','normalized', ...
    'Position',[0.08 0.58 0.84 0.26], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',fg, ...
    'FontName','Arial', ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'String','DVARS  recommended', ...
    'Value',1, ...
    'UserData','DVARS');

uicontrol('Parent',methodGroup, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',[0.12 0.40 0.80 0.16], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',fgDim, ...
    'FontName','Arial', ...
    'FontSize',10, ...
    'HorizontalAlignment','left', ...
    'String','Detects sudden frame-to-frame signal changes.');

rbGS = uicontrol('Parent',methodGroup, ...
    'Style','radiobutton', ...
    'Units','normalized', ...
    'Position',[0.08 0.13 0.84 0.25], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',fg, ...
    'FontName','Arial', ...
    'FontSize',13, ...
    'String','Global Signal', ...
    'Value',0, ...
    'UserData','Global Signal');

set(methodGroup,'SelectedObject',rbDVARS);

% ---------------------------------------------------------------------
% Interpolation method
% ---------------------------------------------------------------------
interpGroup = uibuttongroup('Parent',dlg, ...
    'Units','normalized', ...
    'Position',[0.52 0.59 0.44 0.23], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',fg, ...
    'Title','Replacement of flagged volumes', ...
    'FontName','Arial', ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'BorderType','line');

rbLinear = uicontrol('Parent',interpGroup, ...
    'Style','radiobutton', ...
    'Units','normalized', ...
    'Position',[0.08 0.58 0.84 0.26], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',fg, ...
    'FontName','Arial', ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'String','Linear  recommended', ...
    'Value',1, ...
    'UserData','linear');

uicontrol('Parent',interpGroup, ...
    'Style','text', ...
    'Units','normalized', ...
    'Position',[0.12 0.40 0.80 0.16], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',fgDim, ...
    'FontName','Arial', ...
    'FontSize',10, ...
    'HorizontalAlignment','left', ...
    'String','Stable and conservative for fUSI time-series.');

uicontrol('Parent',interpGroup, ...
    'Style','radiobutton', ...
    'Units','normalized', ...
    'Position',[0.08 0.13 0.84 0.25], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',fg, ...
    'FontName','Arial', ...
    'FontSize',13, ...
    'String','PCHIP', ...
    'Value',0, ...
    'UserData','pchip');

set(interpGroup,'SelectedObject',rbLinear);

% ---------------------------------------------------------------------
% Trimming panel
% ---------------------------------------------------------------------
trimPanel = uipanel('Parent',dlg, ...
    'Units','normalized', ...
    'Position',[0.04 0.25 0.92 0.27], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',fg, ...
    'Title','Optional trimming', ...
    'FontName','Arial', ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'BorderType','line');

cbTrim = uicontrol('Parent',trimPanel, ...
    'Style','checkbox', ...
    'Units','normalized', ...
    'Position',[0.04 0.68 0.50 0.20], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',fg, ...
    'FontName','Arial', ...
    'FontSize',13, ...
    'FontWeight','bold', ...
    'String','Enable trimming before scrubbing', ...
    'Value',0, ...
    'Callback',@toggleTrim);

uicontrol('Parent',trimPanel,'Style','text', ...
    'Units','normalized', ...
    'Position',[0.58 0.68 0.36 0.20], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',cyanCol, ...
    'FontName','Arial', ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'String','Default: no trimming');

uicontrol('Parent',trimPanel,'Style','text', ...
    'Units','normalized', ...
    'Position',[0.04 0.37 0.22 0.18], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',fg, ...
    'FontName','Arial', ...
    'FontSize',12, ...
    'HorizontalAlignment','left', ...
    'String','Trim START sec:');

editStart = uicontrol('Parent',trimPanel,'Style','edit', ...
    'Units','normalized', ...
    'Position',[0.26 0.39 0.18 0.18], ...
    'BackgroundColor',bg3, ...
    'ForegroundColor',fg, ...
    'FontName','Arial', ...
    'FontSize',12, ...
    'String','30', ...
    'Enable','off');

uicontrol('Parent',trimPanel,'Style','text', ...
    'Units','normalized', ...
    'Position',[0.52 0.37 0.22 0.18], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',fg, ...
    'FontName','Arial', ...
    'FontSize',12, ...
    'HorizontalAlignment','left', ...
    'String','Trim END sec:');

editEnd = uicontrol('Parent',trimPanel,'Style','edit', ...
    'Units','normalized', ...
    'Position',[0.72 0.39 0.18 0.18], ...
    'BackgroundColor',bg3, ...
    'ForegroundColor',fg, ...
    'FontName','Arial', ...
    'FontSize',12, ...
    'String','30', ...
    'Enable','off');

uicontrol('Parent',trimPanel,'Style','text', ...
    'Units','normalized', ...
    'Position',[0.04 0.10 0.92 0.18], ...
    'BackgroundColor',bg2, ...
    'ForegroundColor',fgDim, ...
    'FontName','Arial', ...
    'FontSize',10, ...
    'HorizontalAlignment','left', ...
    'String','Use trimming only when the first/last seconds are unstable. Otherwise keep no trimming.');

% ---------------------------------------------------------------------
% Error/status text
% ---------------------------------------------------------------------
statusTxt = uicontrol('Parent',dlg,'Style','text', ...
    'Units','normalized', ...
    'Position',[0.04 0.17 0.92 0.04], ...
    'BackgroundColor',bg, ...
    'ForegroundColor',orange, ...
    'FontName','Arial', ...
    'FontSize',11, ...
    'FontWeight','bold', ...
    'HorizontalAlignment','left', ...
    'String','Ready. Defaults are already selected.');

% ---------------------------------------------------------------------
% Buttons
% ---------------------------------------------------------------------
uicontrol('Parent',dlg,'Style','pushbutton', ...
    'String','Run Scrubbing', ...
    'Units','normalized', ...
    'Position',[0.54 0.055 0.24 0.08], ...
    'FontName','Arial', ...
    'FontWeight','bold', ...
    'FontSize',13, ...
    'BackgroundColor',green, ...
    'ForegroundColor','w', ...
    'Callback',@onRun);

uicontrol('Parent',dlg,'Style','pushbutton', ...
    'String','Cancel', ...
    'Units','normalized', ...
    'Position',[0.80 0.055 0.16 0.08], ...
    'FontName','Arial', ...
    'FontWeight','bold', ...
    'FontSize',13, ...
    'BackgroundColor',red, ...
    'ForegroundColor','w', ...
    'Callback',@onCancel);

uicontrol('Parent',dlg,'Style','pushbutton', ...
    'String','Use Recommended', ...
    'Units','normalized', ...
    'Position',[0.04 0.055 0.22 0.08], ...
    'FontName','Arial', ...
    'FontWeight','bold', ...
    'FontSize',12, ...
    'BackgroundColor',blue, ...
    'ForegroundColor','w', ...
    'Callback',@onRecommended);

set(dlg,'Visible','on');
uiwait(dlg);

if ishandle(dlg)
    delete(dlg);
end

% ---------------------------------------------------------------------
% Nested callbacks
% ---------------------------------------------------------------------
    function toggleTrim(~,~)
        if get(cbTrim,'Value') == 1
            set(editStart,'Enable','on');
            set(editEnd,'Enable','on');
            set(statusTxt,'String','Trimming enabled. Enter start/end seconds.');
        else
            set(editStart,'Enable','off');
            set(editEnd,'Enable','off');
            set(statusTxt,'String','No trimming selected.');
        end
    end

    function onRecommended(~,~)
        set(methodGroup,'SelectedObject',rbDVARS);
        set(interpGroup,'SelectedObject',rbLinear);
        set(cbTrim,'Value',0);
        set(editStart,'Enable','off','String','30');
        set(editEnd,'Enable','off','String','30');
        set(statusTxt,'String','Recommended defaults restored: DVARS + Linear + No trimming.');
    end

    function onRun(~,~)

        detObj = get(methodGroup,'SelectedObject');
        intObj = get(interpGroup,'SelectedObject');

        if isempty(detObj) || isempty(intObj)
            set(statusTxt,'ForegroundColor',[1.00 0.35 0.35], ...
                'String','Please select detection and interpolation method.');
            return;
        end

        doTrimNow = get(cbTrim,'Value') == 1;

        startSec = 0;
        endSec   = 0;

        if doTrimNow
            startSec = str2double(get(editStart,'String'));
            endSec   = str2double(get(editEnd,'String'));

            if ~isfinite(startSec) || startSec < 0
                set(statusTxt,'ForegroundColor',[1.00 0.35 0.35], ...
                    'String','Invalid START trim. Enter a number >= 0.');
                return;
            end

            if ~isfinite(endSec) || endSec < 0
                set(statusTxt,'ForegroundColor',[1.00 0.35 0.35], ...
                    'String','Invalid END trim. Enter a number >= 0.');
                return;
            end
        end

        cfg.cancelled    = false;
        cfg.method       = get(detObj,'UserData');
        cfg.interpMethod = get(intObj,'UserData');
        cfg.doTrim       = doTrimNow;
        cfg.trimStartSec = startSec;
        cfg.trimEndSec   = endSec;

        if ishandle(dlg)
            uiresume(dlg);
        end
    end

    function onCancel(~,~)
        cfg.cancelled = true;
        if ishandle(dlg)
            uiresume(dlg);
        end
    end

end
end
