%% deConfUSIon FINAL STABILIZE - atlas_tools path + remove patch clutter
% Purpose:
%   Final stabilization before full 2D / 2D step-motor testing.
%
% This patch:
%   1) Keeps atlas_tools and makes JM atlas files discoverable there.
%   2) Fixes deConfUSIon_prepare_atlas.m so it finds:
%        atlas_tools/rgb2acr.xlsx
%        atlas_tools/list_selected_regions.txt
%   3) Fixes deConfUSIon_fc_jm_order.m so FC ordering finds:
%        atlas_tools/list_selected_regions.txt
%   4) Archives deConfUSIon_dropdown_metadata_repair.m from root because it is
%      now only a repair patch, not runtime code.
%   5) Writes a final decision report.
%
% This patch does NOT delete backups. Keep backups until your full test passes.
%
% Usage:
%   run('D:\Github\HUMOR-Analysis-Tool\deConfUSIon_final_stabilize_atlas_and_clutter.m')

clearvars -except root
clc

if exist('root','var') ~= 1 || isempty(root)
    root = 'D:\Github\HUMOR-Analysis-Tool';
end
root = char(regexprep(root,'[\\/]+$',''));

if exist(root,'dir') ~= 7
    error('Toolbox root not found: %s', root);
end

stamp = datestr(now,'yyyymmdd_HHMMSS');
archiveRoot = fullfile(root,'backups',['deConfUSIon_final_stabilize_' stamp]);
beforeEditDir = fullfile(archiveRoot,'before_edit');
patchClutterDir = fullfile(archiveRoot,'archived_patch_clutter');
mkdir(archiveRoot);
mkdir(beforeEditDir);
mkdir(patchClutterDir);

fprintf('\n=== deConfUSIon FINAL STABILIZE ===\n');
fprintf('ROOT   : %s\n', root);
fprintf('ARCHIVE: %s\n\n', archiveRoot);

logFile = fullfile(archiveRoot,'final_stabilize_log.tsv');
fidLog = fopen(logFile,'w');
fprintf(fidLog,'action\tstatus\tsource\tdestination\tdetails\n');

%% Make sure atlas_tools exists and is on path when testing
atlasTools = fullfile(root,'atlas_tools');
if exist(atlasTools,'dir') ~= 7
    mkdir(atlasTools);
end
addpath(root,'-begin');
addpath(atlasTools,'-begin');

%% 1) Fix deConfUSIon_prepare_atlas.m
prepFile = fullfile(root,'deConfUSIon_prepare_atlas.m');
if exist(prepFile,'file') == 2
    copyfile(prepFile, fullfile(beforeEditDir,'deConfUSIon_prepare_atlas_before_final_stabilize.m'));

    L = { ...
'function atlas = deConfUSIon_prepare_atlas(atlas, atlasPath)' ...
'% deConfUSIon_prepare_atlas  Automatic JM atlas color/order preparation.' ...
'% This does not change atlas geometry. It adds corrected rgb fields and stores' ...
'% selected/reordered region indices in atlas.deConfUSIon.' ...
'' ...
'if nargin < 2, atlasPath = ''''; end' ...
'try' ...
'    here = fileparts(mfilename(''fullpath''));' ...
'    if isempty(here), here = pwd; end' ...
'' ...
'    [listFile, rgbFile] = localFindJmAtlasFiles(here);' ...
'' ...
'    if exist(rgbFile,''file'') == 2' ...
'        atlas = deConfUSIon_apply_rgb2acr(atlas, rgbFile);' ...
'    end' ...
'' ...
'    if isstruct(atlas) && isfield(atlas,''infoRegions'') && exist(listFile,''file'') == 2' ...
'        D = readFileList(listFile, atlas.infoRegions);' ...
'        selected_regions = [];' ...
'        try' ...
'            selected_regions = cat(2,D.parts{:});' ...
'        catch' ...
'            selected_regions = [];' ...
'        end' ...
'        selected_regions = unique(selected_regions,''stable'');' ...
'        atlas.deConfUSIon.selected_regions = selected_regions;' ...
'        atlas.deConfUSIon.selected_region_list_file = listFile;' ...
'        atlas.deConfUSIon.rgb2acr_file = rgbFile;' ...
'        atlas.deConfUSIon.selected_region_groups = D;' ...
'        if isfield(atlas.infoRegions,''acr'')' ...
'            try, atlas.deConfUSIon.acr_reordered = atlas.infoRegions.acr(selected_regions); catch, end' ...
'        end' ...
'        if ~isempty(atlasPath)' ...
'            try, atlas.deConfUSIon.source_atlas_path = atlasPath; catch, end' ...
'        end' ...
'    end' ...
'catch ME' ...
'    warning(''deConfUSIon:PrepareAtlas'',''JM atlas preparation skipped: %s'', ME.message);' ...
'end' ...
'end' ...
'' ...
'function [listFile, rgbFile] = localFindJmAtlasFiles(here)' ...
'% Prefer root if present, otherwise atlas_tools.' ...
'listFile = fullfile(here,''list_selected_regions.txt'');' ...
'rgbFile  = fullfile(here,''rgb2acr.xlsx'');' ...
'' ...
'atlasDir = fullfile(here,''atlas_tools'');' ...
'if exist(listFile,''file'') ~= 2' ...
'    cand = fullfile(atlasDir,''list_selected_regions.txt'');' ...
'    if exist(cand,''file'') == 2, listFile = cand; end' ...
'end' ...
'if exist(rgbFile,''file'') ~= 2' ...
'    cand = fullfile(atlasDir,''rgb2acr.xlsx'');' ...
'    if exist(cand,''file'') == 2, rgbFile = cand; end' ...
'end' ...
'end' ...
};

    writeCellFile(prepFile,L);
    fprintf('PATCHED: deConfUSIon_prepare_atlas.m now searches atlas_tools.\n');
    fprintf(fidLog,'PATCH_PREPARE_ATLAS\tPATCHED\t%s\t\t\n',prepFile);
else
    fprintf('WARNING: deConfUSIon_prepare_atlas.m missing.\n');
    fprintf(fidLog,'PATCH_PREPARE_ATLAS\tMISSING\t%s\t\t\n',prepFile);
end

%% 2) Fix deConfUSIon_fc_jm_order.m
fcOrderFile = fullfile(root,'deConfUSIon_fc_jm_order.m');
if exist(fcOrderFile,'file') == 2
    copyfile(fcOrderFile, fullfile(beforeEditDir,'deConfUSIon_fc_jm_order_before_final_stabilize.m'));

    L = { ...
'function [ord, ok, score] = deConfUSIon_fc_jm_order(labels, names, listFile)' ...
'% deConfUSIon_fc_jm_order  Reorder FC ROI names according to JM list.' ...
'% The function returns ord into the input arrays. Unmatched regions are kept' ...
'% after matched regions in their original order.' ...
'' ...
'if nargin < 3 || isempty(listFile)' ...
'    here = fileparts(mfilename(''fullpath''));' ...
'    listFile = localFindJmListFile(here);' ...
'end' ...
'labels = labels(:);' ...
'if nargin < 2 || isempty(names)' ...
'    names = cell(numel(labels),1);' ...
'    for i = 1:numel(labels), names{i} = sprintf(''ROI_%g'',labels(i)); end' ...
'end' ...
'names = cellstr(names(:));' ...
'ord = (1:numel(names))'';' ...
'ok = false;' ...
'score = 0;' ...
'if exist(listFile,''file'') ~= 2 || isempty(names)' ...
'    return;' ...
'end' ...
'' ...
'jm = localReadJmTokens(listFile);' ...
'if isempty(jm), return; end' ...
'rank = inf(numel(names),1);' ...
'for i = 1:numel(names)' ...
'    nm = lower(localCleanName(names{i}));' ...
'    best = inf;' ...
'    for j = 1:numel(jm)' ...
'        tok = lower(localCleanName(jm{j}));' ...
'        if isempty(tok), continue; end' ...
'        if strcmp(nm,tok) || ~isempty(strfind(nm,tok)) || ~isempty(strfind(tok,nm))' ...
'            best = j;' ...
'            break;' ...
'        end' ...
'    end' ...
'    rank(i) = best;' ...
'end' ...
'matched = isfinite(rank);' ...
'score = sum(matched);' ...
'if any(matched)' ...
'    [~,ix] = sortrows([rank(:) (1:numel(rank))'']);' ...
'    ord = ix(:);' ...
'    ok = true;' ...
'end' ...
'end' ...
'' ...
'function listFile = localFindJmListFile(here)' ...
'listFile = fullfile(here,''list_selected_regions.txt'');' ...
'if exist(listFile,''file'') ~= 2' ...
'    cand = fullfile(here,''atlas_tools'',''list_selected_regions.txt'');' ...
'    if exist(cand,''file'') == 2, listFile = cand; end' ...
'end' ...
'end' ...
'' ...
'function tokens = localReadJmTokens(listFile)' ...
'tokens = {};' ...
'fid = fopen(listFile,''r'');' ...
'if fid < 0, return; end' ...
'closer = onCleanup(@() fclose(fid)); %#ok<NASGU>' ...
'while true' ...
'    ln = fgetl(fid);' ...
'    if ~ischar(ln), break; end' ...
'    raw = strtrim(ln);' ...
'    if isempty(raw), continue; end' ...
'    if numel(raw) >= 2 && strcmp(raw(1:2),''//''), continue; end' ...
'    cpos = strfind(raw,''//'');' ...
'    if ~isempty(cpos), raw = strtrim(raw(1:cpos(1)-1)); end' ...
'    if isempty(raw), continue; end' ...
'    if raw(1) == ''%'', raw = strtrim(raw(2:end)); end' ...
'    toks = regexp(raw,''\s+'',''split'');' ...
'    toks = toks(~cellfun(''isempty'',toks));' ...
'    if isempty(toks), continue; end' ...
'    tokens{end+1,1} = toks{1}; %#ok<AGROW>' ...
'end' ...
'end' ...
'' ...
'function s = localCleanName(s)' ...
's = char(s);' ...
's = regexprep(s,''^[LR][\-_\s]+'','''');' ...
's = regexprep(s,''\s*\([LR]\)\s*$'','''');' ...
's = regexprep(s,''left|right'','''');' ...
's = regexprep(s,''[^A-Za-z0-9]+'','''');' ...
'end' ...
};

    writeCellFile(fcOrderFile,L);
    fprintf('PATCHED: deConfUSIon_fc_jm_order.m now searches atlas_tools.\n');
    fprintf(fidLog,'PATCH_FC_JM_ORDER\tPATCHED\t%s\t\t\n',fcOrderFile);
else
    fprintf('WARNING: deConfUSIon_fc_jm_order.m missing.\n');
    fprintf(fidLog,'PATCH_FC_JM_ORDER\tMISSING\t%s\t\t\n',fcOrderFile);
end

%% 3) Archive repair patch from root after successful use
repairPatch = fullfile(root,'deConfUSIon_dropdown_metadata_repair.m');
if exist(repairPatch,'file') == 2
    moveOne(repairPatch, fullfile(patchClutterDir,'deConfUSIon_dropdown_metadata_repair.m'), fidLog, 'ARCHIVE_REPAIR_PATCH');
end

%% 4) Verify required atlas assets
assetReport = fullfile(archiveRoot,'final_atlas_tools_check.txt');
fidA = fopen(assetReport,'w');
fprintf(fidA,'deConfUSIon atlas_tools check\n');
fprintf(fidA,'Generated: %s\n\n', datestr(now));

requiredAssets = { ...
    fullfile(root,'atlas_tools','rgb2acr.xlsx'), ...
    fullfile(root,'atlas_tools','list_selected_regions.txt'), ...
    fullfile(root,'readFileList.m'), ...
    fullfile(root,'deConfUSIon_apply_rgb2acr.m'), ...
    fullfile(root,'deConfUSIon_prepare_atlas.m'), ...
    fullfile(root,'deConfUSIon_fc_jm_order.m') ...
};

for i = 1:numel(requiredAssets)
    if exist(requiredAssets{i},'file') == 2
        fprintf(fidA,'OK      %s\n', requiredAssets{i});
        fprintf('OK: %s\n', requiredAssets{i});
    else
        fprintf(fidA,'MISSING %s\n', requiredAssets{i});
        fprintf('MISSING: %s\n', requiredAssets{i});
    end
end
fclose(fidA);

%% 5) Final decision report
decisionFile = fullfile(archiveRoot,'final_cleanup_decisions.txt');
fidD = fopen(decisionFile,'w');
fprintf(fidD,'Final cleanup decision summary\n');
fprintf(fidD,'==============================\n\n');
fprintf(fidD,'atlas_tools: KEEP. Contains rgb2acr.xlsx and list_selected_regions.txt. These are needed for JM color/order support.\n');
fprintf(fidD,'backups: KEEP until full testing with normal 2D and 2D step-motor data passes. After that, copy/zip backups outside the repository and then delete the backups folder if desired.\n');
fprintf(fidD,'run_fusi_studio.m: KEEP. deConfUSIon.m launches through it; it assembles the split GUI/runtime.\n');
fprintf(fidD,'save_correct_colors.m: OPTIONAL MANUAL TOOL in atlas_tools. Keep if you want manual atlas RGB fixing; automatic registration does not call it.\n');
fprintf(fidD,'studio_load_options_dark_dialog.m: KEEP. Runtime load options dialog.\n');
fprintf(fidD,'studio_resolve_paths.m: KEEP. Used by group/studio path resolution.\n');
fprintf(fidD,'studio_mkdir.m: KEEP if present. It is referenced by fusi_studio_GUI.m.\n');
fprintf(fidD,'dropdown metadata helpers: KEEP. Needed for saved preprocessing outputs to appear correctly in dropdowns.\n');
fprintf(fidD,'popup/autofit helpers: KEEP. GUI/timer callback helpers should remain external.\n');
fprintf(fidD,'FC/step-motor helpers: KEEP. Shared across FC/studio/step-motor workflows.\n');
fclose(fidD);

%% 6) Path cleanup and final checks
removeBackupReportPaths(root);
addpath(root,'-begin');
addpath(atlasTools,'-begin');
rehash;
clear functions;

fprintf('\nDONE. Final stabilization completed.\n');
fprintf('Archive/log folder: %s\n', archiveRoot);
fprintf('Atlas check report: %s\n', assetReport);
fprintf('Decision report   : %s\n', decisionFile);

fprintf('\nNow run:\n');
fprintf('  which deConfUSIon_prepare_atlas\n');
fprintf('  which deConfUSIon_fc_jm_order\n');
fprintf('  deConfUSIon\n');

fprintf(fidLog,'SUMMARY\tDONE\t\t\t\n');
fclose(fidLog);

%% Local helpers
function writeCellFile(target,L)
    fid = fopen(target,'w');
    if fid < 0
        error('Could not open target for writing: %s', target);
    end
    for ii = 1:numel(L)
        fprintf(fid,'%s\n',L{ii});
    end
    fclose(fid);
end

function moveOne(src,dst,fidLog,action)
    if exist(src,'file') ~= 2 && exist(src,'dir') ~= 7
        fprintf('SKIP missing: %s\n',src);
        fprintf(fidLog,'%s\tMISSING\t%s\t%s\t\n',action,src,dst);
        return;
    end
    dd = fileparts(dst);
    if exist(dd,'dir') ~= 7
        mkdir(dd);
    end
    finalDst = dst;
    if exist(finalDst,'file') == 2 || exist(finalDst,'dir') == 7
        [p,n,e] = fileparts(dst);
        finalDst = fullfile(p,[n '_' datestr(now,'HHMMSSFFF') e]);
    end
    try
        movefile(src,finalDst);
        fprintf('MOVED: %s -> %s\n',src,finalDst);
        fprintf(fidLog,'%s\tMOVED\t%s\t%s\t\n',action,src,finalDst);
    catch ME
        fprintf('FAILED: %s -> %s | %s\n',src,finalDst,ME.message);
        fprintf(fidLog,'%s\tFAILED\t%s\t%s\t%s\n',action,src,finalDst,ME.message);
    end
end

function removeBackupReportPaths(root)
    badRoots = {fullfile(root,'backups'), fullfile(root,'bakcups'), fullfile(root,'cleanup_reports')};
    for bi = 1:numel(badRoots)
        if exist(badRoots{bi},'dir') ~= 7
            continue;
        end
        pp = regexp(genpath(badRoots{bi}), pathsep, 'split');
        for pi = 1:numel(pp)
            if isempty(pp{pi}), continue; end
            if ~isempty(strfind(path, pp{pi}))
                try, rmpath(pp{pi}); catch, end %#ok<CTCH>
            end
        end
    end
end
