"""Generate a navigable inventory and static symbol-dependency map."""
from pathlib import Path
import csv
import hashlib
import re
from collections import defaultdict

ROOT = Path(__file__).resolve().parents[1]
FILES = sorted([*ROOT.glob('*.m'), *(ROOT / 'lib').rglob('*.m'),
                *(ROOT / 'atlas_tools').glob('*.m'), *(ROOT / 'acquisition').rglob('*.m')])
FILES = [p for p in FILES if p.name != 'Contents.m']
BY_NAME = {p.stem: p for p in FILES}
DEPENDENCIES = {}
CALLERS = defaultdict(list)

def relative(path):
    return path.relative_to(ROOT).as_posix()

for path in FILES:
    source = path.read_text(encoding='utf-8-sig')
    # Studio's embedded callback source is also searched intentionally.
    code = '\n'.join(line.split('%', 1)[0] for line in source.splitlines()
                     if not line.lstrip().startswith('%'))
    calls = set(re.findall(r'\b([A-Za-z]\w*)\s*\(', code))
    calls.update(re.findall(r'@([A-Za-z]\w*)', code))
    local = set(re.findall(r'^\s*function\s+(?:\[[^\]]*\]\s*=\s*|\w+\s*=\s*)?(\w+)', source, re.M))
    dependencies = sorted(BY_NAME[name] for name in calls
                          if name in BY_NAME and name not in local and BY_NAME[name] != path)
    DEPENDENCIES[path] = dependencies
    for dep in dependencies:
        CALLERS[dep].append(path)

docs = ROOT / 'docs'
with (docs / 'code_dependencies.csv').open('w', newline='', encoding='utf-8') as stream:
    writer = csv.writer(stream)
    writer.writerow(['Caller', 'Dependency', 'Evidence'])
    for source, dependencies in DEPENDENCIES.items():
        for dep in dependencies:
            writer.writerow([relative(source), relative(dep), 'Static function call / callback symbol'])
with (docs / 'code_inventory.csv').open('w', newline='', encoding='utf-8') as stream:
    writer = csv.writer(stream)
    writer.writerow(['Path', 'Lines', 'Bytes', 'SHA256', 'Dependencies', 'Referenced_by'])
    for path in FILES:
        data = path.read_bytes()
        writer.writerow([relative(path), len(data.splitlines()), len(data), hashlib.sha256(data).hexdigest(),
                         '; '.join(map(relative, DEPENDENCIES[path])), '; '.join(map(relative, CALLERS[path]))])

groups = defaultdict(list)
for path in FILES:
    group = relative(path.parent) if path.parent != ROOT else 'Public entry points and legacy APIs'
    groups[group].append(path)
lines = ['# Toolbox source map', '',
         f'{len(FILES)} active MATLAB files; {sum(len(p.read_bytes().splitlines()) for p in FILES):,} lines including comments.', '',
         'Generated by `python maintenance/build_code_map.py`. Backups, validation outputs and tests are excluded from this runtime inventory.', '',
         'Calls below are static symbol references, not proof that a branch executes. Dynamic `feval`, assembled Studio callbacks, MATLAB toolbox functions and external ITK-SNAP/Greedy tools require additional review.', '',
         'The root holds supported launchers and public APIs. `lib` holds implementation modules. Run `deConfUSIon_setup` when using helpers directly; GUI entry points do this automatically. Never add backup directories to the MATLAB path.', '',
         '## Main workflows', '',
         '```mermaid', 'flowchart TD',
         '  deConfUSIon --> run_fusi_studio',
         '  run_fusi_studio --> fusi_studio_GUI',
         '  run_fusi_studio --> fusi_studio_callback',
         '  fusi_studio_callback --> DataIO',
         '  fusi_studio_callback --> Preprocessing',
         '  fusi_studio_callback --> SCM_gui',
         '  SCM_gui <--> play_fusi_video_final',
         '  play_fusi_video_final --> fusiVolumeGUI',
         '  fusiVolumeGUI --> registration_ccf',
         '  registration_ccf --> AtlasRegistration',
         '  AtlasRegistration --> Atlas_modules',
         '  fusi_studio_callback --> Segmentation',
         '  Segmentation --> FunctionalConnectivity',
         '  SCM_gui --> GroupAnalysis',
         '  FunctionalConnectivity --> GroupAnalysis_FC',
         '```', '',
         '## File-by-file dependencies', '',
         'The CSV versions are [inventory](code_inventory.csv) and [dependency edges](code_dependencies.csv).', '']
for group, paths in sorted(groups.items()):
    lines.extend(['### ' + group, '', '| Script | Lines | Calls in toolbox | Referenced by |', '|---|---:|---|---|'])
    for path in paths:
        def links(items):
            return ', '.join(f'[{p.stem}](../{relative(p)})' for p in items) or '—'
        lines.append(f'| [{path.name}](../{relative(path)}) | {len(path.read_bytes().splitlines()):,} | {links(DEPENDENCIES[path])} | {links(CALLERS[path])} |')
    lines.append('')
(docs / 'code_map.md').write_text('\n'.join(lines) + '\n', encoding='utf-8')
for group in (ROOT / 'lib').iterdir():
    if not group.is_dir():
        continue
    content = [f'% {group.name.upper()} - deConfUSIon implementation module.',
               '% Initialize with deConfUSIon_setup; see docs/code_map.md for callers.']
    for path in sorted(group.glob('*.m')):
        if path.name == 'Contents.m':
            continue
        content.append('%   ' + path.stem)
    (group / 'Contents.m').write_text('\n'.join(content) + '\n', encoding='utf-8')
print(f'Generated runtime inventory for {len(FILES)} MATLAB files and {sum(map(len, DEPENDENCIES.values()))} dependency edges.')
